### ISSUE TITLE
About Transformer Block

### ISSUE THREAD

**Issue by Berry-Wu** [HowieMa/PPT#5]
Hi, I have a question about the code in tokenpose_base.py of Transformer: why remove the first residual of Attention. I see the code in TokenPose dosen't remove it. And in your paper ,i can't find the reason.

**Comment by HowieMa** [comment]
Hi, thanks for your interest in our work. 
Actually, we still have the residual layer, as you can see from [here](https://github.com/HowieMa/PPT/blob/main/single-view-PPT/lib/models/tokenpose_base.py#L132). So, we don't need to talk about it in the paper.

**Comment by Berry-Wu** [comment]
Sorry, I missed your reply. It was my fault, thank you for your reply！:)
