### ISSUE TITLE
About token purned

### ISSUE THREAD

**Issue by helloyuning** [HowieMa/PPT#6]
Tanks for your greate work and sharing.

I have some questions:

1. where is the code of pured pose.
2. How to decide purned rate(how much pixels will be purned)

Tanks ,
yuning

**Comment by HowieMa** [comment]
Hi, thanks for your interest in our work.
Can you specify your question 1? I don't fully understand it. Do you refer to the trained network or the detailed implementation of the models?
As for question 2, the pruning ratio is an empirical number. It is a trade-off between efficiency and accuracy. As for COCO, we find that a prune ratio of 0.7 would be fine. You can see the ablation study in our paper for more details.

**Comment by helloyuning** [comment]
> 
I would like to ask where the specific code implementation of prune step is, It seems that the code of the model does not include this part.

thanks

**Comment by HowieMa** [comment]
This code does include the pruning step. As we only prune the tokens, rather than the network weights, we only need to make a slight change on TokenPose. 
You can find the detailed token pruning part at this [code](https://github.com/HowieMa/PPT/blob/main/single-view-PPT/lib/models/tokenpose_base.py#L141).

**Comment by helloyuning** [comment]
Thank you so much!  发件人: Haoyu Ma发送时间: 2023년 3월 21일 화요일 오후 7:23收件人: HowieMa/PPT抄送: helloyuning; Author主题: Re: [HowieMa/PPT] About token purned (Issue #6) This code does include the pruning step. As we only prune the tokens, rather than the network weights, we only need to make a slight change on TokenPose.You can find the detailed token pruning part at this code.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
